# Generated by Django 4.2 on 2023-08-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_order_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amounnt',
            new_name='amount',
        ),
    ]
